### ISSUE TITLE
Incorrect Validation Query in DB2DataSourceCreator

### ISSUE THREAD

**Issue by aperdec** [spring-cloud/spring-cloud-connectors#200] opened 2017-05-10 18:52 UTC
When trying to use the validation query while connecting to DB2, an error "Failed to validate a newly established connection" is produced. This is caused by the validation query "VALUES 1". A tested and recommended fix for this would be to change the validation query to "SELECT 1 FROM sysibm.sysdummy1".

**Comment by scottfrederick** [comment] 2017-05-11 17:25
This is a duplicate of #187. No changes were made in response to that issue because I could not get confirmation that one validation query is appropriate for all DB2 configurations. `VALUES 1` seems to work for some users, including the person who contributed the original code. Is `SELECT 1 FROM sysibm.sysdummy1` guaranteed to work for all DB2 configurations? Is this specific to the version of DB2? The change is simple to make, but I'd like to be sure it doesn't help some users while hurting others. 

In the interim, a workaround was provided here: https://github.com/spring-cloud/spring-cloud-connectors/issues/187#issuecomment-277292931.

**Comment by scottfrederick** [comment] 2017-10-20 22:02
Closing this issue for lack of feedback and a viable workaround.

**Closed by scottfrederick** 2017-10-20 22:02 UTC
Labels: blocked, service-connector
