### ISSUE TITLE
Spring-cloud XML data-source should allow configuration of validationQuery, etc.

### ISSUE THREAD

**Issue by sdeeg-pivotal** [spring-cloud/spring-cloud-connectors#150] opened 2015-11-11 01:08 UTC
Currently the only way to set properties on the data source is via JavaConfig.  Users of XML need the ability to set these properties.

@scottfrederick - let me know if you need more details.

**Comment by scottfrederick** [comment] 2015-11-19 23:40
Duplicate of #144

**Closed by scottfrederick** 2015-11-19 23:40 UTC
Labels: spring-connector
